### ISSUE TITLE
Add a tip about variable formats

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla-l10n/langchecker#311]
We have a tip about {ok} tags in a yellow box on the locale page, Miroslav our Bulgarian localizer suggests that we also explain our replacement variables format because he found it confusing at first and thought that the ending s was a mistake.

It's probably a good idea as I have already seen others being confused with it and either removing the final s or translating the variable itself. Taking.

**Comment by TheoChevalier** [comment]
shamefully stealing from Pascal
