### ISSUE TITLE
missing font

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla-l10n/langchecker#416]
I see in the logs that we have a missing font file:
127.0.0.1:35260 [404]: /assets/assets/fonts/OpenSans-Bold-webfont.woff - No such file or directory

Could be the opportunity to check if we shouldn't simplify our font loading or even switch to Fira since I think we will go with it on mozilla.org soon

**Comment by flodolo** [comment]
We simplified the fonts (following Transvision) recently, so it's a bit weird.
https://github.com/mozilla-l10n/langchecker/commit/a66bc4682c7e31f15cf9de42a37dec944aede9d9
