### ISSUE TITLE
Update the list of iOS and Fennec locales

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/langchecker#531]
# iOS
Ignore the part about stores_l10n
https://github.com/mozilla-l10n/langchecker/blob/master/app/config/locales.inc.php#L47-L64

The latest version is in
https://raw.githubusercontent.com/mozilla/firefox-ios/v5.x/shipping_locales.txt

# Android
https://github.com/mozilla-l10n/langchecker/blob/master/app/config/locales.inc.php#L79-L94

We need to double check the list of locales with
http://hg.mozilla.org/releases/mozilla-aurora/raw-file/tip/mobile/android/locales/maemo-locales

If you want, we can add Kabyle to this list to enable some of the pages.

Once added, you will need to run lang_update to actually add the new files, as usual.

**Comment by peiying2** [comment]
both sets of locales have some mis-match ones.  https://docs.google.com/spreadsheets/d/198MK2xQgRgHU4CyH2NmY3xFt_ZkR8DCN9KhDtBiHOF4/edit#gid=464837506

**Comment by flodolo** [comment]
Thanks, I left some note in the doc. All the files missing from the langchecker column should be added, excluding only be.

**Comment by flodolo** [comment]
I should also take the habit of filing an issue here every time we update locales in Android and iOS, I have the feeling these lists haven't been updated in months.
