### ISSUE TITLE
Remove references to obsolete plugincheck and firefox/new

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/langchecker#535]
We need to remove from config:
- `firefox/new.lang` (replaced by `firefox/new/horizon.lang`)
- `mozorg/plugincheck.lang` (replaced by `mozorg/plugincheck-redesign.lang`)

**Comment by peiying2** [comment]
Another one is this new page: https://www.mozilla.org/en-US/about/leadership/.  Do we want to remove the old one?  The new one is not required to be localized, though nice to have in languages where MoCo has and office.

**Comment by flodolo** [comment]
I'm quite sure we already removed that months ago.
