### ISSUE TITLE
'/usr/share/file/magic' doesn’t work on Mac and homebrew

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-l10n/langchecker#577]
Error in the PHP server logs: https://pastebin.mozilla.org/8965227

**Comment by flodolo** [comment]
This is interesting. I set up langchecker on Mac, using the internal PHP web server, but I don't get any error and everything works out of the box.

Do you have a `/usr/share/file/magic` folder on your Mac?

**Comment by TheoChevalier** [comment]
weird… I do have this folder, yes (and it’s loaded with stuff). Are you on 10.12.2 too?

**Comment by flodolo** [comment]
I've tested on 10.11.6 (15G1212), I can try 10.12.2 later

**Comment by flodolo** [comment]
Also, are you using php internal server or apache?

**Comment by TheoChevalier** [comment]
using internal PHP server 7.0.14, installed via homebrew. Maybe a homebrew related nonsense?

**Comment by flodolo** [comment]
Definitely. I'm using the default php
```
$ php --version
PHP 5.5.38 (cli) (built: Aug 21 2016 21:48:49)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```
I can give it a try with homebrew.

**Comment by flodolo** [comment]
I think you're hitting
https://bugs.php.net/bug.php?id=66885

Trying to figure out if we can at least not die like that
