### ISSUE TITLE
Issue with translations starting with "#"

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-l10n/langchecker#641]
Edge case here, 2 translations are starting with a hashtag https://github.com/mozilla-l10n/engagement-l10n/blob/master/fr/snippets/2017/jun2017.lang

Strings are reported as identical https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=snippets/2017/jun2017.lang

**Comment by flodolo** [comment]
I don't think it's a bug that we can fix (it would invalidate all the assumptions that we make when parsing the file), it's a known limitation of the format and there's not much that we can do about it. 

Also note that we are not the only parser for this format out there (Pootle, Pontoon, Bedrock), and this would be read as a comment. You can argue that this should happen only with snippets, but the parser change would be all over the place.

We have similar limitations in .properties (you can't use ; in a plural form).

I think you need to work around this limitation, adding a special character at the beginning (or a space) would be enough.

**Comment by flodolo** [comment]
OK, adding a space ignore these strings completely and throws errors. We need a workaround :-\
