### ISSUE TITLE
'es' ignored in usage percentages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-l10n/langchecker#667]
Not sure if we want to fix this, but just noticed that the percentage of our l10n user base does not take into account the ’es’ locale, probably missing a sum of percentages for es-ES, es-AR…

**Comment by flodolo** [comment]
Reality is that those percentages are quite often off (I've seen more than 100% at times), and they were born for mozilla.org coverage.

Having said, it should be relatively easy to fix.
