### ISSUE TITLE
Drop stale locales from mozilla.org

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/langchecker#869]
We're removing a few locales from Firefox and Fennec, I think it makes sense to remove them from mozilla.org as well:
* as: 10%
* en-ZA: not enabled in Pontoon
* mai: 10%
* or: 10%

The only one that makes sense to keep is ml, since they're at 71%.

@peiying2 Thoughts on this?

**Comment by peiying2** [comment]
Let's remove them. I would have expected a longer list than this.

**Comment by flodolo** [comment]
> Let's remove them. I would have expected a longer list than this.

This is only based on the fact that we're removing them from Firefox. I expect to have more locales in this situation, but that would be your call ;-)

**Comment by peiying2** [comment]
Spring cleaning. Add to the to-do list, :).

**Comment by flodolo** [comment]
Removed
