### ISSUE TITLE
Remove .lang files already migrated

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/langchecker#983]
Let's remove .lang files already migrated to prevent further update activities between now and the switch (May 22). I am not able to identify all the migrated source files as they are not 1 to 1. Here are a few that I can identify but there could be more so please update this list. We plan to send email communications to l10n communities on May 15, it would be great if we remove them before the email is sent out. 

Reference:
- Migrated files: https://github.com/mozmeao/www-l10n/tree/master/metadata
- .lang https://github.com/mozilla-l10n/langchecker/blob/master/app/config/sources.inc.php

Firefox/new/download.ftl 
- firefox/campaign-trailhead.lang, 
- firefox/new/quantum.lang

mozorg/mission.ftl 
- mozorg/mission.lang

download_button.ftl
- download_button.lang

footer.ftl
- footer.lang

navigation.ftl
- navigation.lang

newsletter_form.ftl
- mozorg/newsletters.lang

send_to_device.ftl 
- firefox/sendto.lang

Other to be included (?)
- main.lang
- mozorg/contribute/index.lang

*NOTE*:
DO NOT remove: These two files will be resynced on May 20th. 
- firefox/all-unified.lang, 
- firefox/new/trailhead.lang

**Comment by peiying2** [comment]
@alexgibson feel free to assign the task to other devs.

**Comment by alexgibson** [comment]
> firefox/campaign-trailhead.lang
> firefox/new/quantum.lang
> mozorg/newsletters.lang
> main.lang
> mozorg/contribute/index.lang
> firefox/all-unified.lang,
> firefox/new/trailhead.lang

These files can't be removed yet as are still in use.
